main : Electro\TellRaw\TellRaw
name: TellRaw
version: 3.0.0
api: 5.0.0
Author: Electro

commands:
 tellraw:
  description: Send people messages anonymously
  permission: tellraw.cmd
    
permissions:
 tellraw.cmd:
  description: Permission to execute the tellraw command
  default: op

